### PR TITLE
Delete unused classes

### PR DESCRIPTION
**Pull request by AnthonySteele**
_Summarise the changes this Pull Request makes._

Delete unused classes `PoolAwareSocketAsyncEventArgs` and `SimpleObjectPool`
We stopped using these in the last release, but the code is still there

_Please include a reference to a GitHub issue if appropriate._

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Check away. They are `public` :( but I doubt it. 

In the unlikely case that someone is, they should copy the source into their  app.

**Comment by martincostello** [comment]
Yeah, I do use these. I use them in a alternate `IStatsDTransport` implementation to pool `UdpClient` instances.

**Comment by AnthonySteele** [comment]
So is that use just in one place? would you rather have these classes in `JustEat.StatsD` or with the alternate `IStatsDTransport` implementation?

**Comment by martincostello** [comment]
I guess it's easy enough for me to copy them over at whatever point I upgrade to StatsD 3, but I thought I'd point it out as it's another breaking change.

**Comment by martincostello** [comment]
See #81, where we _might_ want to at least use `SimpleObjectPool`.

**Comment by AnthonySteele** [comment]
Will review this later. We might make them internal and/or sealed

**Pull request closed without merging**
