### PR TITLE
Fix package description

### LINKED ISSUE #45: Package description for NuGet is wrong
Oops. Looks like we broke this since 1.1.0.

image

### PR DESCRIPTION
**Pull request by martincostello**
* Add a package description/summary for NuGet.
  * Bump the version to `2.0.1`.

Resolves #45.

### CODE REVIEW

**Comment by martincostello** [comment]
@slang25 What black magic sets the version number? I can't find it and the version is still coming out as 2.0.0 in the CI builds.

**Comment by stuart-lang** [comment]
Looks like this: https://github.com/justeat/JustEat.StatsD/blob/master/JustEat.StatsD.Common.props#L18

**Comment by stuart-lang** [comment]
Here's what we do in JustSaying: https://github.com/justeat/JustSaying/blob/master/version.props

**Comment by martincostello** [comment]
🤦‍♂️ dammit - I looked for that and completely missed it...

**Comment by martincostello** [comment]
We can make the approach consistent between the repos in another PR.

**Pull request merged**
